import {useCallback,useEffect,useRef,useState,type CSSProperties,type FormEvent,type ReactNode} from 'react';
import {AnimatePresence,motion,useInView,useReducedMotion,useScroll,useTransform} from 'motion/react';
import {CalendarDays,Check,Copy,MapPin,Music2,Pause,Share2} from 'lucide-react';
import {ArrowRight,ArrowUpRight} from '../components/EditorialArrow';
import {useLanguage} from '../i18n';
import event from '../content/omarSara.json';
import {useWeddingMusic} from './useWeddingMusic';
import OmarEnvelopeEntrance from './OmarEnvelopeEntrance';
import './omar-sara.css';

const copy={
 en:{names:['Omar','Sara'],kicker:'TOGETHER WITH OUR FAMILIES',invite:'We invite you to celebrate our wedding',navDay:'The evening',navLocation:'Location',navReply:'RSVP',forever:'Our forever begins here.',intro:'Some moments become a part of you. This is ours, and we would love to share it with the people who mean the most to us.',dateLabel:'THE DATE',venueLabel:'THE SETTING',countdown:'UNTIL WE CELEBRATE TOGETHER',days:'Days',hours:'Hours',minutes:'Minutes',seconds:'Seconds',arrived:'The day is here.',calendar:'Save the date',google:'Google Calendar',download:'Apple / Outlook',saved:'Invitation link copied',share:'Share invitation',scroll:'DISCOVER OUR EVENING',storyLabel:'A LITTLE LOVE. A LIFETIME AHEAD.',storyTitle:'One evening. A beautiful beginning.',story:'A room full of our favourite people, the warmth of a shared table, and the start of something wonderful. Your presence will make this day a memory we carry forever.',quote:'All the beautiful tomorrows, beginning with you.',timelineLabel:'THE EVENING',timelineTitle:'Every moment, together.',venueTitle:'Meet us at the Four Seasons.',venueText:'An evening in the heart of Amman. We cannot wait to welcome you.',directions:'Get directions',showVenue:'Four Seasons Hotel Amman',detailsLabel:'A FEW THOUGHTFUL DETAILS',dress:'Evening elegance',dressText:'Formal evening attire. Wear something that makes you feel wonderful.',arrival:'A little early, a little more time',arrivalText:'Join us from 6:30 PM. Our celebration begins at 7:00 PM, Amman time.',travel:'Coming from out of town?',travelText:'Find travel and hotel information directly with Four Seasons Amman.',hotelInfo:'Hotel & travel information',rsvpTitle:'We saved you a place.',rsvpIntro:'Let us know whether you will join us for the celebration.',guest:'Your name',guestHint:'How should we welcome you?',reply:'Your reply',yes:'Joyfully accept',no:'Regretfully decline',guests:'Guests, including you',note:'A note for Omar & Sara',noteHint:'A few words from the heart…',consent:'I agree to share my reply with the hosts under the',privacy:'Privacy Policy',submit:'Send my reply',sending:'Sending your reply…',thanks:'Your reply is with Omar & Sara.',thanksText:'Thank you for letting us know. We look forward to celebrating together.',error:'We could not confirm your reply. Please try again shortly.',soon:'Attendance confirmations will open soon.',closed:'Attendance confirmations are now closed.',footer:'With love,',credit:'Invitation by Invitéa',optional:'Optional',replyDeadline:'Kindly let us know by January 3, 2027.'},
 ar:{names:['عمر','سارة'],kicker:'بكل المحبة، وبحضور أهلنا وأحبابنا',invite:'ندعوكم لمشاركتنا فرحة زفافنا',navDay:'أمسيتنا',navLocation:'المكان',navReply:'تأكيد الحضور',forever:'هنا، تبدأ حكايتنا معاً.',intro:'في العمر لحظات تستقرّ في القلب. وهذه لحظتنا؛ نودّ أن نشاركها مع من نحبّ، لتصبح ذكرى يحلو لنا أن نرويها.',dateLabel:'الموعد',venueLabel:'المكان',countdown:'نعدّ الأيام حتى نلقاكم',days:'أيام',hours:'ساعات',minutes:'دقائق',seconds:'ثوانٍ',arrived:'حان يوم فرحتنا.',calendar:'احفظ الموعد',google:'تقويم Google',download:'Apple / Outlook',saved:'نُسخ رابط الدعوة',share:'شارك الدعوة',scroll:'تفاصيل فرحتنا',storyLabel:'محبة تجمعنا، وعمر نبدأه',storyTitle:'أمسية واحدة، وبداية عمر.',story:'أحبابنا حولنا، ودفء اللقاء يجمعنا، وفرحة نخطو بها أولى خطوات العمر معاً. بحضوركم، تصبح هذه اللحظة ذكرى نحفظها دائماً في قلوبنا.',quote:'كل الغد الجميل، يبدأ بك.',timelineLabel:'تفاصيل الأمسية',timelineTitle:'على الفرح، نلتقي.',venueTitle:'نلقاكم في فورسيزونز.',venueText:'في قلب عمّان، نجتمع على المحبة ونشارككم أمسيتنا الأجمل.',directions:'افتح مسار الوصول',showVenue:'فندق فورسيزونز عمّان',detailsLabel:'تفاصيل تهمّ أحبابنا',dress:'إطلالة أنيقة للأمسية',dressText:'ملابس رسمية مسائية، وإطلالة تشعركم بالجمال والراحة.',arrival:'نرحّب بكم قبل بداية الفرح',arrivalText:'نستقبلكم من السادسة والنصف مساءً، ويبدأ الاحتفال عند السابعة، بتوقيت عمّان.',travel:'تزورون عمّان من بعيد؟',travelText:'يمكنكم الاطّلاع على معلومات الإقامة والوصول لدى فورسيزونز عمّان.',hotelInfo:'معلومات الفندق والوصول',rsvpTitle:'مكانكم محفوظ في قلوبنا.',rsvpIntro:'أخبرونا إن كنتم ستشاركوننا هذه الفرحة.',guest:'الاسم',guestHint:'بأي اسم نرحّب بكم؟',reply:'هل تشاركوننا الفرحة؟',yes:'بكل سرور، سنحضر',no:'نعتذر عن الحضور',guests:'عدد الحضور، بمن فيهم أنت',note:'كلمة لعمر وسارة',noteHint:'كلماتكم الجميلة تسعدنا…',consent:'أوافق على مشاركة ردّي مع أصحاب المناسبة وفق',privacy:'سياسة الخصوصية',submit:'أرسل الردّ',sending:'جارٍ إرسال ردّك…',thanks:'وصل ردّك إلى عمر وسارة.',thanksText:'شكراً لإخبارنا. نتطلّع إلى مشاركة هذه الأمسية الجميلة معكم.',error:'تعذّر تأكيد وصول ردّك. يرجى المحاولة بعد قليل.',soon:'نفتح باب تأكيد الحضور قريباً.',closed:'انتهت فترة تأكيد الحضور.',footer:'بكل المحبة،',credit:'دعوة من تصميم Invitéa',optional:'اختياري',replyDeadline:'نرجو تأكيد الحضور قبل ٣ يناير ٢٠٢٧.'}
};
const petalPositions=[8,17,29,42,54,66,78,89,23,48,72,94];
const musicCopy={en:{play:'Play wedding music',pause:'Pause wedding music',label:'Music',hint:'Touch the invitation to begin the music.',error:'The music could not start. Tap the music button to try again.'},ar:{play:'شغّل موسيقى الأمسية',pause:'أوقف الموسيقى مؤقتاً',label:'موسيقى',hint:'المس الدعوة لتبدأ موسيقى الأمسية.',error:'تعذّر تشغيل الموسيقى. اضغط على زر الموسيقى للمحاولة مرة أخرى.'}};
function Reveal({children,className=''}:{children:ReactNode;className?:string}){
 const reduced=useReducedMotion();
 return <motion.div className={className} initial={reduced?false:{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.8,ease:[.22,1,.36,1]}}>{children}</motion.div>;
}
function utc(value:Date){return value.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');}
function calendarFile(start:Date){
 const escape=(value:string)=>value.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
 const end=new Date(start.getTime()+4*3600000);
 const calendar=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Invitea//Omar and Sara//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:omar-sara-wedding-invitea',`DTSTAMP:${utc(new Date())}`,`DTSTART:${utc(start)}`,`DTEND:${utc(end)}`,'SUMMARY:Omar & Sara - Wedding',`LOCATION:${escape(event.venue.name.en+', '+event.venue.address.en)}`,'DESCRIPTION:We look forward to celebrating with you. Arrival from 6:30 PM.','END:VEVENT','END:VCALENDAR',''].join('\r\n');
 const url=URL.createObjectURL(new Blob([calendar],{type:'text/calendar;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='omar-sara-wedding.ics';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function Countdown({date}:{date:Date}){
 const {lang}=useLanguage();const t=copy[lang];const [now,setNow]=useState(Date.now);
 useEffect(()=>{const timer=setInterval(()=>{if(!document.hidden)setNow(Date.now());},1000);return()=>clearInterval(timer);},[]);
 const seconds=Math.max(0,Math.floor((date.getTime()-now)/1000));const values=[Math.floor(seconds/86400),Math.floor(seconds/3600)%24,Math.floor(seconds/60)%60,seconds%60];
 return <div className="os-countdown"><span className="os-label">{t.countdown}</span>{seconds>0?<div role="timer" aria-live="off" aria-label={t.countdown}>{values.map((value,i)=><span key={i}><strong>{new Intl.NumberFormat(lang,{minimumIntegerDigits:2,useGrouping:false}).format(value)}</strong><small>{[t.days,t.hours,t.minutes,t.seconds][i]}</small></span>)}</div>:<p>{t.arrived}</p>}</div>;
}
export default function OmarSaraInvitation(){
 const {lang,setLang}=useLanguage();const t=copy[lang];const reduced=useReducedMotion();const hero=useRef<HTMLElement>(null);const visible=useInView(hero);
 const [entered,setEntered]=useState(false);const audio=useRef<HTMLAudioElement>(null);const sound=useWeddingMusic(audio,entered);const musicText=musicCopy[lang];
 const requiresOpening=!entered;const revealInvitation=useCallback(()=>setEntered(true),[]);
 useEffect(()=>{
  if(!requiresOpening)return;
  const previous=document.body.style.overflow;document.body.style.overflow='hidden';
  return()=>{document.body.style.overflow=previous;};
 },[requiresOpening]);
 function openInvitation(){void sound.start();}
 const {scrollYProgress}=useScroll({target:hero,offset:['start start','end start']});const parallax=useTransform(scrollYProgress,[0,1],['0%','12%']);
 const [eventDate,setEventDate]=useState(event.eventDate);const [availability,setAvailability]=useState<'loading'|'ready'|'soon'|'closed'>('loading');const [maxGuests,setMaxGuests]=useState(5);const [collectMessage,setCollectMessage]=useState(true);
 const [attendance,setAttendance]=useState('yes');const [status,setStatus]=useState<'idle'|'sending'|'done'>('idle');const [error,setError]=useState('');const [shared,setShared]=useState(false);
 const date=new Date(eventDate);const dateText=new Intl.DateTimeFormat(lang==='ar'?'ar-JO':'en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:event.timeZone}).format(date);const weekday=new Intl.DateTimeFormat(lang==='ar'?'ar-JO':'en-GB',{weekday:'long',timeZone:event.timeZone}).format(date);
 const timeText=new Intl.DateTimeFormat(lang==='ar'?'ar-JO':'en-GB',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:event.timeZone}).format(date);
 const coordinate=`${event.venue.latitude},${event.venue.longitude}`;const map=`https://www.google.com/maps/search/?api=1&query=${coordinate}`;const directions=`https://www.google.com/maps/dir/?api=1&destination=${coordinate}`;
 const calendar=new URL('https://calendar.google.com/calendar/render');calendar.search=new URLSearchParams({action:'TEMPLATE',text:'Omar & Sara · Wedding',dates:`${utc(date)}/${utc(new Date(date.getTime()+4*3600000))}`,details:'Arrival from 6:30 PM. We look forward to celebrating with you.',location:`${event.venue.name.en}, ${event.venue.address.en}`,ctz:event.timeZone}).toString();
 useEffect(()=>{document.title=lang==='ar'?'زفاف عمر وسارة · ١٠ يناير ٢٠٢٧':'Omar & Sara · 10 January 2027';},[lang]);
 useEffect(()=>{
  const controller=new AbortController();
  fetch(`/api/invitations/${event.slug}`,{signal:controller.signal,cache:'no-store'}).then(async response=>{
   if(!response.ok){if(!controller.signal.aborted)setAvailability('soon');return;}
   const {invitation}=await response.json();
   if(invitation?.slug!==event.slug||invitation?.status!=='published'){setAvailability('soon');return;}
   if(typeof invitation.eventDate==='string'&&Number.isFinite(new Date(invitation.eventDate).getTime()))setEventDate(invitation.eventDate);
   setMaxGuests(Math.max(1,Math.min(20,Number(invitation.features?.maxGuests)||5)));setCollectMessage(invitation.features?.collectMessage===true);
   setAvailability(invitation.features?.rsvp===true?'ready':'closed');
  }).catch(()=>{if(!controller.signal.aborted)setAvailability('soon');});
  return()=>controller.abort();
 },[]);
 async function share(){try{const url=location.href.split('#')[0];if(navigator.share)await navigator.share({title:'Omar & Sara',url});else{await navigator.clipboard.writeText(url);setShared(true);}}catch{setShared(false);}}
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();if(availability!=='ready'||status==='sending'||status==='done')return;const data=new FormData(e.currentTarget);setError('');setStatus('sending');
  try{const response=await fetch(`/api/invitations/${event.slug}/rsvp`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guestName:String(data.get('guestName')||'').trim(),attendance,guestCount:attendance==='yes'?Number(data.get('guestCount')):0,...(collectMessage?{message:String(data.get('message')||'')}:{}),privacyAccepted:data.get('privacy')==='on',website:String(data.get('website')||'')})});
   if(response.status===410){setAvailability('closed');setStatus('idle');return;}if(!response.ok)throw new Error();const result=await response.json();if(result.received!==true)throw new Error();setStatus('done');
  }catch{setStatus('idle');setError(t.error);}
 }
 return <div className={`omar-sara ${visible?'os-scene-visible':''}`} lang={lang} dir={lang==='ar'?'rtl':'ltr'}>
  <audio ref={audio} src={event.music.src} autoPlay={entered} loop preload="auto" onPlaying={sound.onPlaying} onPause={sound.onPause} onError={sound.onError}/>
  <AnimatePresence onExitComplete={()=>document.getElementById('os-main')?.focus({preventScroll:true})}>
   {requiresOpening&&<OmarEnvelopeEntrance lang={lang} onOpen={openInvitation} onOpened={revealInvitation} onLanguage={()=>setLang(lang==='en'?'ar':'en')}/>}
  </AnimatePresence>
  <div className={`os-invitation-content ${requiresOpening?'is-sealed':''}`} inert={requiresOpening} aria-hidden={requiresOpening}>
  <a href="#os-main" className="os-skip">{lang==='ar'?'انتقل إلى الدعوة':'Skip to invitation'}</a>
  <header className="os-navigation"><a className="os-monogram" href="#os-main" aria-label={lang==='ar'?'عمر وسارة':'Omar & Sara'} dir="ltr">O<span>&</span>S</a><nav aria-label={lang==='ar'?'أقسام الدعوة':'Invitation sections'}><a href="#os-evening">{t.navDay}</a><a href="#os-location">{t.navLocation}</a><a href="#os-rsvp">{t.navReply}</a></nav><div><button onClick={share} aria-label={t.share} className="os-share">{shared?<Check size={17}/>:<Share2 size={17}/>}</button><button className="os-language" onClick={()=>setLang(lang==='en'?'ar':'en')}>{lang==='en'?'عربي':'EN'}</button></div></header>
  <main id="os-main" tabIndex={-1}><section className="os-hero" ref={hero}>
   <motion.div className="os-scene" style={{y:reduced?0:parallax}} aria-hidden="true"><img src="/invitations/omar-sara/garden-hero.webp" width="1536" height="1024" alt="" fetchPriority="high"/></motion.div><div className="os-hero-shade" aria-hidden="true"/>
   <div className="os-petals" aria-hidden="true">{petalPositions.map((x,i)=><i key={i} style={{'--x':`${x}%`,'--delay':`${-i*3.2}s`,'--duration':`${27+i%4*5}s`,'--drift':`${(i%2===0?1:-1)*(35+i*4)}px`} as CSSProperties}/>)}</div>
   <img className="os-botanical os-botanical-left" src="/invitations/omar-sara/garden-botanicals.webp" width="550" height="825" alt=""/><img className="os-botanical os-botanical-right" src="/invitations/omar-sara/garden-botanicals.webp" width="550" height="825" alt=""/>
   <div className="os-hero-copy"><motion.p className="os-label" initial={reduced?false:{opacity:0}} animate={{opacity:entered?1:0}} transition={{duration:.9}}>{t.kicker}</motion.p><h1 aria-label={t.names.join(lang==='ar'?' و ':' & ')}>{t.names.map((name,i)=><span className="os-name-mask" key={name}><motion.span initial={reduced?false:{y:'105%'}} animate={{y:reduced||entered?0:'105%'}} transition={{duration:1,delay:.15+i*.12,ease:[.22,1,.36,1]}}>{i===1&&<em aria-hidden="true">&</em>}{name}</motion.span></span>)}</h1><motion.div initial={reduced?false:{opacity:0,y:15}} animate={{opacity:entered?1:0,y:reduced||entered?0:15}} transition={{duration:.8,delay:.45}}><p className="os-hero-invite">{t.invite}</p><span className="os-hairline"/><time dateTime={eventDate}>{dateText}<span> · </span>{timeText}</time><p className="os-hero-venue">{event.venue.name[lang]}</p><a className="os-button os-button-light" href="#os-rsvp">{t.navReply}<ArrowRight/></a></motion.div></div><a className="os-discover" href="#os-story">{t.scroll}<span/></a>
  </section>
  <section className="os-story" id="os-story"><Reveal><span className="os-label">{t.storyLabel}</span><h2>{t.storyTitle}</h2><p>{t.story}</p><span className="os-hairline"/><blockquote>{t.quote}</blockquote></Reveal><Reveal className="os-story-image"><img src="/invitations/omar-sara/garden-details.webp" width="850" height="1275" alt={lang==='ar'?'أزهار عاجية وضوء شموع لطابع الأمسية':'Ivory flowers and candlelight for the evening'} loading="lazy"/><span>{t.forever}</span></Reveal></section>
  <section className="os-date-section"><Reveal><Countdown date={date}/><div className="os-event-date"><span className="os-label">{weekday}</span><h2>{dateText}</h2><p>{timeText} · {lang==='ar'?'بتوقيت عمّان':'Amman time'}</p></div><div className="os-calendar"><span><CalendarDays size={18}/>{t.calendar}</span><a className="os-text-link" href={calendar.href} target="_blank" rel="noopener noreferrer">{t.google}<ArrowUpRight/></a><button className="os-text-link" onClick={()=>calendarFile(date)}>{t.download}<ArrowRight/></button></div></Reveal></section>
  <section className="os-evening" id="os-evening"><Reveal><span className="os-label">{t.timelineLabel}</span><h2>{t.timelineTitle}</h2><ol>{event.schedule.map((step,i)=><li key={step.time}><span className="os-timeline-number">0{i+1}</span><time dateTime={step.time}>{new Intl.DateTimeFormat(lang==='ar'?'ar-JO':'en-GB',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:'UTC'}).format(new Date(`2000-01-01T${step.time}:00Z`))}</time><div><h3>{step.title[lang]}</h3><p>{step.text[lang]}</p></div></li>)}</ol></Reveal></section>
  <section className="os-venue" id="os-location"><Reveal className="os-venue-photo"><img src="/invitations/omar-sara/four-seasons.webp" alt={t.showVenue} loading="lazy" width="1000" height="1000"/><span className="os-label">{t.showVenue}</span></Reveal><Reveal className="os-venue-copy"><span className="os-label">{t.venueLabel}</span><h2>{t.venueTitle}</h2><p>{t.venueText}</p><div className="os-address"><MapPin size={19}/><address>{event.venue.address[lang]}</address></div><a href={directions} target="_blank" rel="noopener noreferrer" className="os-button">{t.directions}<ArrowUpRight/></a></Reveal><div className="os-map"><iframe title={lang==='ar'?'موقع فندق فورسيزونز عمّان':'Four Seasons Hotel Amman location'} src={`https://www.google.com/maps?q=${coordinate}&z=16&output=embed`} loading="lazy" referrerPolicy="strict-origin-when-cross-origin"/><a className="os-map-caption" href={map} target="_blank" rel="noopener noreferrer">{t.showVenue}<ArrowUpRight/></a></div></section>
  <section className="os-guest-notes"><span className="os-label">{t.detailsLabel}</span><div>{[[t.dress,t.dressText],[t.arrival,t.arrivalText],[t.travel,t.travelText]].map(([title,text],i)=><Reveal key={title}><span className="os-note-number">0{i+1}</span><h3>{title}</h3><p>{text}</p>{i===2&&<a className="os-text-link" href={lang==='ar'?'https://www.fourseasons.com/ar/amman/getting-here/':event.venue.source} target="_blank" rel="noopener noreferrer">{t.hotelInfo}<ArrowUpRight/></a>}</Reveal>)}</div></section>
  <section className="os-rsvp" id="os-rsvp"><Reveal className="os-rsvp-intro"><span className="os-label">RSVP</span><h2>{t.rsvpTitle}</h2><p>{t.rsvpIntro}</p><small>{t.replyDeadline}</small><img src="/invitations/omar-sara/garden-botanicals.webp" alt="" width="550" height="825" loading="lazy"/></Reveal>
   {status==='done'?<div className="os-reply-success" role="status"><Check size={32} strokeWidth={1}/><h3>{t.thanks}</h3><p>{t.thanksText}</p></div>:<form className="os-rsvp-form" onSubmit={submit}><fieldset disabled={status==='sending'}><label>{t.guest}<input name="guestName" required maxLength={120} autoComplete="name" placeholder={t.guestHint}/></label><fieldset className="os-attendance"><legend>{t.reply}</legend>{[['yes',t.yes],['no',t.no]].map(([value,label])=><label key={value}><input type="radio" name="attendance" checked={attendance===value} value={value} onChange={()=>setAttendance(value)}/><span>{label}</span></label>)}</fieldset>{attendance==='yes'&&<label>{t.guests}<select name="guestCount" defaultValue="1">{Array.from({length:maxGuests},(_,i)=><option key={i+1} value={i+1}>{new Intl.NumberFormat(lang).format(i+1)}</option>)}</select></label>}{collectMessage&&<label>{t.note}<small>{t.optional}</small><textarea name="message" maxLength={1000} rows={3} placeholder={t.noteHint}/></label>}<label className="os-consent"><input type="checkbox" name="privacy" required/><span>{t.consent} <a href={`/${lang}/privacy`} target="_blank" rel="noopener noreferrer">{t.privacy}</a>.</span></label><label className="os-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button type="submit" className="os-button os-button-light" disabled={availability!=='ready'||status==='sending'}>{status==='sending'?t.sending:t.submit}<ArrowRight/></button></fieldset>{availability==='soon'||availability==='closed'?<p className="os-rsvp-notice" role="status">{availability==='closed'?t.closed:t.soon}</p>:null}{error&&<p className="os-form-error" role="alert">{error}</p>}</form>}
  </section></main>
  <button className={`os-music-toggle ${sound.playing?'is-playing':''}`} data-music-control onClick={sound.toggle} aria-label={sound.playing?musicText.pause:musicText.play} aria-pressed={sound.playing}>{sound.playing?<Pause size={17}/>:<Music2 size={17}/>}<span>{musicText.label}</span></button>
  <span className="os-music-status" role="status">{sound.failed?musicText.error:sound.blocked?musicText.hint:''}</span>
  <footer className="os-footer"><span>{t.footer}</span><p>{t.names[0]} <em>&</em> {t.names[1]}</p><span className="os-label">{dateText} · {event.venue.name[lang]}</span><div><button className="os-text-link" onClick={share}>{shared?t.saved:t.share}{shared?<Check size={15}/>:<Copy size={15}/>}</button><a href={`/${lang}`}>{t.credit}</a></div></footer><span className="os-share-status" role="status">{shared?t.saved:''}</span>
  </div>
 </div>;
}
