import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {AnimatePresence,motion,useInView,useReducedMotion,useScroll,useTransform} from 'motion/react';
import {CalendarDays,Check,MapPin,Music2,Pause,Play,Share2} from 'lucide-react';
import {ArrowRight,ArrowUpRight} from '../components/EditorialArrow';
import {useLanguage} from '../i18n';
import event from '../content/tareqLayan.json';
import ScratchDate from './ScratchDate';
import GuestReply from './GuestReply';
import {BotanicalDrawing,ClassicBackdrop,FrameCorner,MusicRecord,WeddingCrest} from './ClassicArtwork';
import {useWeddingMusic} from './useWeddingMusic';
import EnvelopeEntrance from './EnvelopeEntrance';
import PolaroidGallery from './PolaroidGallery';
import './tareq-layan.css';

const text={
 en:{names:['Tareq','Layan'],together:'TOGETHER WITH OUR FAMILIES',invite:'With full hearts, we invite you to celebrate the beginning of our forever.',heroNote:'A day for love. A lifetime to follow.',discover:'Discover our day',navDate:'The date',navVenue:'The venue',navReply:'RSVP',music:'Play wedding music',musicHint:'Touch the invitation to begin the music.',pause:'Pause wedding music',musicError:'The music could not start. Please try again.',photos:'MOMENTS TO KEEP',photoTitle:'A little collection of forever.',photoText:'The quiet glances. The hands we hold. The beautiful little details. These are the moments our story is made of.',captions:['A beautiful beginning','Hand in hand, always','Little details, lasting memories'],dateLabel:'A LITTLE SURPRISE',dateTitle:'Our day, waiting to be discovered.',scratch:'Scratch to reveal our date',reveal:'Reveal the date instead',revealed:'The date is revealed',dateHint:'Our wedding day',calendar:'Keep a place in your calendar',google:'Google Calendar',download:'Apple / Outlook',countdown:'COUNTING THE MOMENTS',units:['Days','Hours','Minutes','Seconds'],arrived:'Today, our forever begins.',timeline:'THE ORDER OF THE EVENING',timelineTitle:'Every moment, with you.',venueLabel:'THE SETTING',venueTitle:'An evening at the French Mansion.',venueText:'Cream stone, graceful arches, and an evening filled with the people we love. We cannot wait to welcome you.',map:'Get directions',venueCaption:'The place where we celebrate',notes:'A FEW LITTLE DETAILS',dress:'Classic evening elegance',dressText:'We would love to see you in formal evening attire. A classic look, and something that feels like you.',arrival:'Arrive a little early',arrivalText:'Our welcome begins at 6:30 PM. The celebration begins at 7:00 PM, Amman time.',rsvpLabel:'A PLACE FOR YOU',rsvpTitle:'Your presence is our favourite detail.',rsvpText:'Let us know if you will share this beautiful evening with us.',closing:'Some days stay with us forever.',closingText:'This one will, because of you.',love:'With all our love,',share:'Share our invitation',shared:'Invitation link copied',credit:'Invitation by Invitéa',musicCredit:'Music credits',skip:'Skip to invitation',timezone:'Amman time'},
 ar:{names:['طارق','ليان'],together:'بحضور أهلنا وأحبابنا، وبكل المحبة',invite:'ندعوكم لمشاركتنا فرحة زفافنا، وبداية عمر نكتبه معاً بالمودة والرحمة.',heroNote:'فرحة تجمعنا، وحكاية نبدأها معاً.',discover:'اكتشف تفاصيل فرحتنا',navDate:'الموعد',navVenue:'المكان',navReply:'تأكيد الحضور',music:'شغّل موسيقى الأمسية',musicHint:'المس الدعوة لتبدأ موسيقى الأمسية.',pause:'أوقف الموسيقى مؤقتاً',musicError:'تعذّر تشغيل الموسيقى. حاول مرة أخرى.',photos:'لحظات نحفظها في القلب',photoTitle:'تفاصيل صغيرة، وذكريات عمر.',photoText:'نظرة محبة، ويد لا تفارق اليد، وتفاصيل يزداد جمالها حين نشاركها مع من نحبّ. هكذا نبدأ حكايتنا.',captions:['هنا، تبدأ حكايتنا','يداً بيد، دائماً','تفاصيل تبقى في القلب'],dateLabel:'مفاجأة صغيرة لأحبابنا',dateTitle:'موعد فرحتنا، بين يديك.',scratch:'امسح البطاقة لتكتشف الموعد',reveal:'أظهر الموعد مباشرةً',revealed:'اكتشفت موعد فرحتنا',dateHint:'يوم فرحتنا',calendar:'احفظ موعد لقائنا',google:'تقويم Google',download:'Apple / Outlook',countdown:'نعدّ اللحظات حتى نلقاكم',units:['أيام','ساعات','دقائق','ثوانٍ'],arrived:'اليوم، نبدأ حكايتنا معاً.',timeline:'تفاصيل أمسيتنا',timelineTitle:'على المحبة، نلتقي.',venueLabel:'نلقاكم هنا',venueTitle:'أمسية في القصر الفرنسي.',venueText:'بين الأقواس الأنيقة ودفء المكان، نجتمع على فرحنا. بحضوركم، تصبح هذه الأمسية ذكرى نعتزّ بها دائماً.',map:'افتح مسار الوصول',venueCaption:'هنا، نحتفل ببدايتنا',notes:'تفاصيل تهمّ أحبابنا',dress:'إطلالة أنيقة وكلاسيكية',dressText:'نسعد بإطلالة رسمية للأمسية؛ اختر ما يشعرك بالأناقة والراحة، وتعال بقلب يحمل الفرح.',arrival:'نرحّب بكم قبل بداية الفرح',arrivalText:'نستقبلكم من السادسة والنصف مساءً، ويبدأ الاحتفال عند السابعة، بتوقيت عمّان.',rsvpLabel:'مكانكم محفوظ في قلوبنا',rsvpTitle:'بحضوركم، تكتمل فرحتنا.',rsvpText:'أخبرونا إن كنتم ستشاركوننا هذه الأمسية الجميلة.',closing:'في العمر أيام لا ننساها.',closingText:'وهذا يومنا، يكتمل بكم.',love:'بكل المحبة،',share:'شارك الدعوة',shared:'نُسخ رابط الدعوة',credit:'دعوة من تصميم Invitéa',musicCredit:'عن موسيقى الأمسية',skip:'انتقل إلى الدعوة',timezone:'بتوقيت عمّان'}
};

function Ornament({className=''}:{className?:string}){return <svg className={`tl-ornament ${className}`} viewBox="0 0 240 44" fill="none" aria-hidden="true"><path d="M0 22h82m76 0h82M102 22c8-5 11-11 18-17 7 6 10 12 18 17-8 5-11 11-18 17-7-6-10-12-18-17Z" stroke="currentColor" strokeWidth=".8"/><path d="M91 22c7-9 11-4 11 0s-4 9-11 0Zm58 0c-7-9-11-4-11 0s4 9 11 0ZM120 14v16m-8-8h16" stroke="currentColor" strokeWidth=".8"/><circle cx="120" cy="22" r="3" fill="currentColor"/></svg>;}
function Reveal({children,className='',as='div'}:{children:ReactNode;className?:string;as?:'div'|'li'}){const reduced=useReducedMotion();const Tag=as==='li'?motion.li:motion.div;return <Tag className={className} initial={reduced?false:{opacity:0}} whileInView={{opacity:1}} viewport={{once:true,amount:.12}} transition={{duration:.8,ease:[.22,1,.36,1]}}>{children}</Tag>;}
function Polaroid({src,caption,alt,className='',eager=false,rotation=0}:{src:string;caption:string;alt:string;className?:string;eager?:boolean;rotation?:number}){
 const photo=useRef<HTMLElement>(null),reduced=useReducedMotion();
 const inView=useInView(photo,{once:true,amount:.12});
 const {scrollYProgress}=useScroll({target:photo,offset:['start end','end start']});
 const turn=useTransform(scrollYProgress,[0,.5,1],[rotation+2,rotation,rotation-2]);
 const lift=useTransform(scrollYProgress,[0,.5,1],[18,0,-18]);
 const scale=useTransform(scrollYProgress,[0,.5,1],[1.045,1,1.025]);
 return <motion.figure ref={photo} className={`tl-polaroid ${className}`} style={{rotate:reduced?rotation:turn,y:reduced?0:lift}}>
  <div className={inView&&!reduced&&!eager?'tl-photo-developed':''}><motion.img style={{scale:reduced?1:scale}} src={src} alt={alt} width="900" height="1200" loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'}/></div><figcaption>{caption}</figcaption>
 </motion.figure>;
}
function utc(date:Date){return date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');}
function saveCalendar(){const escape=(value:string)=>value.replace(/\\/g,'\\\\').replace(/,/g,'\\,').replace(/;/g,'\\;').replace(/\n/g,'\\n');const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Invitea//Tareq and Layan//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:tareq-layan-wedding-invitea',`DTSTAMP:${utc(new Date())}`,`DTSTART:${utc(new Date(event.eventDate))}`,`DTEND:${utc(new Date(event.endDate))}`,'SUMMARY:Tareq & Layan - Wedding',`LOCATION:${escape(event.venue.name.en+', '+event.venue.address.en)}`,'DESCRIPTION:Arrival from 6:30 PM. We look forward to celebrating with you.','END:VEVENT','END:VCALENDAR',''].join('\r\n');const url=URL.createObjectURL(new Blob([body],{type:'text/calendar;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='tareq-layan-wedding.ics';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Countdown(){const {lang}=useLanguage();const t=text[lang];const [now,setNow]=useState(Date.now);useEffect(()=>{const id=setInterval(()=>{if(!document.hidden)setNow(Date.now());},1000);return()=>clearInterval(id);},[]);const seconds=Math.max(0,Math.floor((new Date(event.eventDate).getTime()-now)/1000));const values=[Math.floor(seconds/86400),Math.floor(seconds/3600)%24,Math.floor(seconds/60)%60,seconds%60];return <div className="tl-countdown"><span className="tl-label">{t.countdown}</span>{seconds?<div role="timer" aria-live="off" aria-label={t.countdown}>{values.map((value,i)=><span key={i}><strong>{new Intl.NumberFormat(lang,{minimumIntegerDigits:2,useGrouping:false}).format(value)}</strong><small>{t.units[i]}</small></span>)}</div>:<p>{t.arrived}</p>}</div>;}

export default function TareqLayanInvitation(){
 const {lang,setLang}=useLanguage();const t=text[lang];const reduced=useReducedMotion();const audio=useRef<HTMLAudioElement>(null);const [opened,setOpened]=useState(false);const sound=useWeddingMusic(audio,opened);const {playing}=sound;const [revealed,setRevealed]=useState(false),[shared,setShared]=useState(false);
 const revealInvitation=useCallback(()=>setOpened(true),[]);
 const date=new Date(event.eventDate),locale=lang==='ar'?'ar-JO':'en-GB';
 const dateText=new Intl.DateTimeFormat(locale,{day:'numeric',month:'long',year:'numeric',timeZone:event.timeZone}).format(date);
 const timeText=new Intl.DateTimeFormat(locale,{hour:'numeric',minute:'2-digit',hour12:true,timeZone:event.timeZone}).format(date);
 const mapQuery=`${event.venue.latitude},${event.venue.longitude}`,map=`https://www.google.com/maps/dir/?api=1&destination=${mapQuery}`;
 const calendar=new URL('https://calendar.google.com/calendar/render');calendar.search=new URLSearchParams({action:'TEMPLATE',text:'Tareq & Layan · Wedding',dates:`${utc(date)}/${utc(new Date(event.endDate))}`,details:'Arrival from 6:30 PM. With all our love, Tareq & Layan.',location:`${event.venue.name.en}, ${event.venue.address.en}`,ctz:event.timeZone}).toString();
 useEffect(()=>{document.title=lang==='ar'?'زفاف طارق وليان · القصر الفرنسي':'Tareq & Layan · The French Mansion';},[lang]);
 async function share(){try{const url=location.href.split('#')[0];if(navigator.share)await navigator.share({title:'Tareq & Layan',url});else{await navigator.clipboard.writeText(url);setShared(true);}}catch{setShared(false);}}
 return <div className="tareq-layan" dir={lang==='ar'?'rtl':'ltr'} lang={lang}>
  <ClassicBackdrop/>
  <audio ref={audio} src={event.music.src} autoPlay={opened} loop preload="auto" onPlaying={sound.onPlaying} onPause={sound.onPause} onError={sound.onError}/>
  <AnimatePresence onExitComplete={()=>document.getElementById('tl-main')?.focus({preventScroll:true})}>
   {!opened&&<EnvelopeEntrance lang={lang} onOpen={()=>{void sound.start();}} onOpened={revealInvitation}/>}
  </AnimatePresence>
  {opened&&<>
  <a className="tl-skip" href="#tl-main">{t.skip}</a>
  <header className="tl-navigation"><a className="tl-monogram" href="#tl-main" aria-label={t.names.join(lang==='ar'?' و ':' & ')} dir="ltr">T<span>&</span>L</a><nav aria-label={lang==='ar'?'أقسام الدعوة':'Invitation sections'}><a href="#tl-date">{t.navDate}</a><a href="#tl-venue">{t.navVenue}</a><a href="#tl-rsvp">{t.navReply}</a></nav><div><button className={`tl-music-toggle ${playing?'is-playing':''}`} aria-label={playing?t.pause:t.music} aria-pressed={playing} data-music-control onClick={sound.toggle}>{playing?<Pause size={17}/>:<Music2 size={17}/>}<span>{playing?t.pause:t.music}</span></button><button className="tl-language" onClick={()=>setLang(lang==='en'?'ar':'en')}>{lang==='en'?'عربي':'EN'}</button></div></header>
  <span className="tl-screen-reader" role="status">{sound.failed?t.musicError:shared&&t.shared}</span>
  <main id="tl-main" tabIndex={-1}><section className="tl-hero"><div className="tl-hero-geometry" aria-hidden="true"><FrameCorner/><FrameCorner className="tl-corner-ne"/><FrameCorner className="tl-corner-se"/><FrameCorner className="tl-corner-sw"/></div><BotanicalDrawing className="tl-hero-bouquet"/><Reveal className="tl-hero-copy"><span className="tl-label">{t.together}</span><WeddingCrest/><h1 aria-label={t.names.join(lang==='ar'?' و ':' & ')}>{t.names[0]}<span><em>{lang==='ar'?'و':'&'}</em>{t.names[1]}</span></h1><p>{t.invite}</p><a className="tl-button" href="#tl-date">{t.discover}<ArrowRight size={24}/></a><span className="tl-hero-footnote">{t.heroNote}</span><span className="tl-sound-note" aria-live="polite">{sound.blocked?<><Music2 size={13}/>{t.musicHint}</>:null}</span></Reveal><Reveal className="tl-hero-art"><div className="tl-photo-back" aria-hidden="true"/><motion.div animate={reduced?undefined:{y:[0,-5,0],rotate:[3,3.8,3]}} transition={{duration:12,repeat:Infinity,ease:'easeInOut'}}><Polaroid eager src="/invitations/tareq-layan/portrait.webp" caption={t.names.join(lang==='ar'?' و ':' & ')} alt={lang==='ar'?'صورة للعروسين في ضوء الشمس الدافئ':'Wedding portrait of a couple in warm sunlight'}/></motion.div><span className="tl-photo-annotation">{t.heroNote}</span></Reveal><div className="tl-hero-edition"><span>{event.venue.name[lang]} · {lang==='ar'?'السلط، الأردن':'AL-SALT, JORDAN'}</span><span>{lang==='ar'?'بالمودة والرحمة':'WITH LOVE, ALWAYS'}</span></div></section>
  <section className="tl-quran" aria-label={lang==='ar'?'آية كريمة من سورة الروم':'A verse from Surah Ar-Rum'}><p className="tl-basmala" lang="ar" dir="rtl">{event.quran.basmala}</p><Ornament/><blockquote lang="ar" dir="rtl">{event.quran.verse}</blockquote><a href={event.quran.source} target="_blank" rel="noopener noreferrer">{event.quran.reference[lang]}</a></section>
  <section className="tl-memories" id="tl-memories"><BotanicalDrawing className="tl-section-sprig"/><Reveal className="tl-section-intro"><span className="tl-label">{t.photos}</span><h2>{t.photoTitle}</h2><p>{t.photoText}</p></Reveal><PolaroidGallery lang={lang} captions={t.captions}/></section>
  <section className="tl-date-section" id="tl-date"><BotanicalDrawing className="tl-date-bouquet"/><Reveal className="tl-section-intro"><span className="tl-label">{t.dateLabel}</span><h2>{t.dateTitle}</h2><Ornament/></Reveal><ScratchDate stamp={new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:event.timeZone}).format(date).replaceAll('/',' / ')} date={dateText} time={`${timeText} · ${t.timezone}`} instruction={t.scratch} revealLabel={t.reveal} revealedLabel={t.revealed} onReveal={()=>setRevealed(true)}/>{revealed&&<div className="tl-calendar"><span><CalendarDays size={17}/>{t.calendar}</span><div><a className="tl-text-link" href={calendar.href} target="_blank" rel="noopener noreferrer">{t.google}<ArrowUpRight size={20}/></a><button className="tl-text-link" onClick={saveCalendar}>{t.download}<ArrowRight size={20}/></button></div></div>}<Countdown/></section>
  <section className="tl-evening"><Reveal className="tl-section-intro"><span className="tl-label">{t.timeline}</span><h2>{t.timelineTitle}</h2></Reveal><ol>{event.schedule.map((step,i)=><Reveal as="li" className="tl-timeline-step" key={step.time}><span className="tl-step-number">0{i+1}</span><time dateTime={step.time}>{new Intl.DateTimeFormat(locale,{hour:'numeric',minute:'2-digit',hour12:true,timeZone:'UTC'}).format(new Date(`2000-01-01T${step.time}:00Z`))}</time><h3>{step.title[lang]}</h3><p>{step.text[lang]}</p></Reveal>)}</ol></section>
  <section className="tl-venue" id="tl-venue"><Reveal className="tl-venue-art"><Polaroid rotation={-3} src="/invitations/tareq-layan/mansion.webp" caption={t.venueCaption} alt={event.venue.name[lang]}/></Reveal><Reveal className="tl-venue-copy"><span className="tl-label">{t.venueLabel}</span><h2>{t.venueTitle}</h2><Ornament/><p>{t.venueText}</p><div className="tl-address"><MapPin size={20}/><address>{event.venue.address[lang]}</address></div><a className="tl-button" href={map} target="_blank" rel="noopener noreferrer">{t.map}<ArrowUpRight size={23}/></a></Reveal><div className="tl-map"><iframe title={lang==='ar'?'موقع القصر الفرنسي':'The French Mansion location'} src={`https://www.google.com/maps?q=${mapQuery}&z=16&output=embed`} loading="lazy" referrerPolicy="strict-origin-when-cross-origin"/><a href={`https://www.google.com/maps/search/?api=1&query=${mapQuery}`} target="_blank" rel="noopener noreferrer">{event.venue.name[lang]}<ArrowUpRight size={18}/></a></div></section>
  <section className="tl-guest-notes"><span className="tl-label">{t.notes}</span><div><Reveal><h3>{t.dress}</h3><p>{t.dressText}</p><span className="tl-dress-swatches" aria-hidden="true"><i/><i/><i/><i/></span></Reveal><Reveal><h3>{t.arrival}</h3><p>{t.arrivalText}</p></Reveal></div></section>
  <section className="tl-rsvp" id="tl-rsvp"><Reveal className="tl-rsvp-copy"><span className="tl-label">{t.rsvpLabel}</span><h2>{t.rsvpTitle}</h2><Ornament/><p>{t.rsvpText}</p><span className="tl-rsvp-initials" aria-hidden="true" dir="ltr">T & L</span></Reveal><GuestReply slug={event.slug}/></section>
  </main>
  <footer className="tl-footer"><WeddingCrest/><h2>{t.closing}</h2><p>{t.closingText}</p><span className="tl-label">{t.love}</span><strong>{t.names.join(lang==='ar'?' و ':' & ')}</strong>{revealed&&<time dateTime={event.eventDate}>{dateText} · {event.venue.name[lang]}</time>}<button className="tl-text-link" onClick={share}>{shared?t.shared:t.share}{shared?<Check size={17}/>:<Share2 size={17}/>}</button><details className="tl-music-credits"><summary>{t.musicCredit}</summary><p><a href={event.music.source} target="_blank" rel="noopener noreferrer">“{event.music.title}” — {event.music.artist} (incompetech.com)</a><br/>Johann Pachelbel · <a href={event.music.license} target="_blank" rel="noopener noreferrer">Creative Commons: By Attribution 4.0</a></p></details><a className="tl-credit" href={`/${lang}`}>{t.credit}</a></footer>
  <button className={`tl-floating-music ${playing?'is-playing':''}`} data-music-control onClick={sound.toggle} aria-label={playing?t.pause:t.music} aria-pressed={playing}><MusicRecord/>{playing?<Pause size={17}/>:<Play size={17}/>}<span>{lang==='ar'?'موسيقى':'Music'}</span></button>
  </>}
 </div>;
}
