import {useEffect,useRef,useState,type ReactNode} from 'react';
import {AnimatePresence,motion,transform,useMotionValueEvent,useReducedMotion,useScroll,useTransform,type MotionValue} from 'motion/react';
import {CalendarDays,Heart,MapPin,Music2,Pause} from 'lucide-react';
import {ArrowRight,ArrowUpRight} from '../components/EditorialArrow';
import {useLanguage,type Lang} from '../i18n';
import event from '../content/yousefRama.json';
import GuestReply from './GuestReply';
import {useWeddingMusic} from './useWeddingMusic';
import '@fontsource/amiri/arabic-400.css';
import '@fontsource/amiri/arabic-700.css';
import '@fontsource/ibm-plex-sans-arabic/arabic-500.css';
import './yousef-rama.css';

const words={
 ar:{opening:'بكل الحب، نشارككم بداية حكايتنا',skip:'ابدأ فرحتنا',sound:'موسيقى الأمسية',pause:'أوقف الموسيقى مؤقتاً',musicHint:'المس الدعوة لتبدأ موسيقى الأمسية.',musicError:'تعذّر تشغيل الموسيقى. حاول مرة أخرى.',together:'بحضور أهلنا وأحبابنا',invite:'يسرّنا أن نشارككم فرحتنا',journey:'اسحب برفق، واكتشف حكايتنا',messageLabel:'دعوة تحمل كل المحبة',messageTitle:'بحضوركم\nتكتمل فرحتنا',message:'نتشرّف بدعوتكم لمشاركتنا أجمل لحظاتنا، والاحتفال معنا ببداية فصل جديد من حياتنا.',messageNote:'لكم مكان في هذه الليلة، وفي قلوبنا دائماً.',countdown:'نعدّ اللحظات حتى نلقاكم',units:['أيام','ساعات','دقائق','ثوانٍ'],arrived:'اليوم، تكتمل فرحتنا بكم.',details:'موعدنا معكم',friday:'الجمعة',date:'١٨ يونيو ٢٠٢٧',time:'٧:٣٠ مساءً',timezone:'بتوقيت عمّان',map:'عرض الموقع',calendar:'احفظ الموعد',eveningLabel:'حين تُضاء عمّان',evening:'تبدأ أمسيتنا،\nوتحلو بكم.',eveningNote:'على المحبة، نلتقي.',schedule:'تفاصيل أمسيتنا',scheduleNote:'من أول لقاء في هذه الليلة، إلى آخر ذكرى جميلة.',dressLabel:'إطلالة تليق بالأمسية',dress:'الزي الرسمي',dressText:'إطلالة مسائية أنيقة، وتفاصيل كلاسيكية تشبهكم. تعالوا بما يشعركم بالجمال والراحة.',photosLabel:'لحظات نحفظها في القلب',photos:'من أول لقاء…\nإلى هذه الليلة',photoNote:'نظرة، ووعد، وتفاصيل صغيرة نصنع منها حكاية عمر.',photoHint:'تابع الحكاية بالتمرير',captions:['حكايتنا، وعمّان شاهدة','حديثنا الأول','تفصيل صغير من فرحتنا'],rsvpLabel:'مكانكم محفوظ في قلوبنا',rsvp:'هل ستشاركوننا فرحتنا؟',rsvpText:'أخبرونا إن كنتم ستشاركوننا هذه الأمسية. حضوركم أجمل تفاصيلها.',closing:'ننتظركم بكل حب',credit:'دعوة من تصميم Invitéa',musicCredit:'عن موسيقى الأمسية',navDate:'الموعد',navReply:'تأكيد الحضور',skipContent:'انتقل إلى الدعوة'},
 en:{opening:'With love, we share the beginning of our story.',skip:'Begin our evening',sound:'Evening music',pause:'Pause evening music',musicHint:'Touch the invitation to start the evening music.',musicError:'The music could not start. Please try again.',together:'TOGETHER WITH OUR FAMILIES',invite:'We invite you to share in our joy',journey:'SCROLL GENTLY. OUR STORY AWAITS.',messageLabel:'AN INVITATION, WITH LOVE',messageTitle:'Our joy is complete\nwith you.',message:'We would be honoured to share this beautiful evening with you, as we begin a new chapter of our lives.',messageNote:'A place in our evening. A place in our hearts.',countdown:'UNTIL WE CELEBRATE TOGETHER',units:['Days','Hours','Minutes','Seconds'],arrived:'Today, our forever begins.',details:'Our evening with you.',friday:'Friday',date:'18 June 2027',time:'7:30 PM',timezone:'Amman time',map:'View location',calendar:'Save the date',eveningLabel:'AS AMMAN LIGHTS UP',evening:'An evening begins.\nA story continues.',eveningNote:'All our favourite people, together.',schedule:'The shape of our evening.',scheduleNote:'From our first welcome to the last beautiful memory.',dressLabel:'A LITTLE EVENING ELEGANCE',dress:'Formal Evening Attire',dressText:'Classic details and a little evening elegance. Wear something that feels wonderful, and entirely like you.',photosLabel:'THE LITTLE THINGS WE KEEP',photos:'From the first hello…\nto this evening.',photoNote:'A glance. A promise. The little things that become a lifetime.',photoHint:'SCROLL TO TURN A MEMORY',captions:['Amman, the beginning of our story','Our first conversation','A little detail of our evening'],rsvpLabel:'A PLACE FOR YOU',rsvp:'Will you share our joy?',rsvpText:'Let us know if you will join our celebration. Your presence is our favourite detail.',closing:'We cannot wait to welcome you.',credit:'Invitation by Invitéa',musicCredit:'Music credits',navDate:'The date',navReply:'RSVP',skipContent:'Skip to invitation'}
};
const photoAlt={ar:['ذكرى مصوّرة مولّدة لعروسين في جبل القلعة بعمّان','صورة مولّدة لفنجاني قهوة على نافذة تطل على تلال جبل عمّان','باقة زفاف عند أعمدة جبل القلعة وتلال عمّان، صورة مولّدة'],en:['Generated candid couple memory at the Amman Citadel','Generated memory of two coffee cups at a window overlooking Jabal Amman','Generated wedding bouquet at the Amman Citadel, with the city hills behind']};
function useRange<T extends number|string>(progress:MotionValue<number>,input:number[],output:T[]){return useTransform(progress,value=>transform(value,input,output));}
function Flourish({className=''}:{className?:string}){return <svg className={`yr-flourish ${className}`} viewBox="0 0 250 36" fill="none" aria-hidden="true"><path d="M0 18h89m72 0h89M110 18l15-11 15 11-15 11-15-11ZM97 18c7-7 11-7 11 0s-4 7-11 0Zm56 0c-7-7-11-7-11 0s4 7 11 0Z" stroke="currentColor" strokeWidth=".8"/><path d="M125 13v10m-5-5h10" stroke="currentColor" strokeWidth=".8"/></svg>;}
function Corners(){return <svg className="yr-corners" viewBox="0 0 1000 650" preserveAspectRatio="none" fill="none" aria-hidden="true"><path d="M25 105V25h80M895 25h80v80M975 545v80h-80M105 625H25v-80M40 80V40h40m840 0h40v40m0 490v40h-40M80 610H40v-40" stroke="currentColor" strokeWidth="1"/></svg>;}
function Reveal({children,className='',as='div'}:{children:ReactNode;className?:string;as?:'div'|'li'}){const reduced=useReducedMotion();const Tag=as==='li'?motion.li:motion.div;return <Tag className={className} initial={reduced?false:{clipPath:'inset(16% 0 0 0)',y:24,opacity:.4}} whileInView={{clipPath:'inset(0% 0 0 0)',y:0,opacity:1}} viewport={{once:true,amount:.15}} transition={{duration:1,ease:[.22,1,.36,1]}}>{children}</Tag>;}
function Lines({text}:{text:string}){return <>{text.split('\n').map((line,i)=><span key={i}>{line}</span>)}</>;}
function Countdown({lang}:{lang:Lang}){
 const [now,setNow]=useState(Date.now);const t=words[lang];
 useEffect(()=>{const timer=setInterval(()=>{if(!document.hidden)setNow(Date.now());},1000);return()=>clearInterval(timer);},[]);
 const seconds=Math.max(0,Math.floor((new Date(event.eventDate).getTime()-now)/1000));const values=[Math.floor(seconds/86400),Math.floor(seconds/3600)%24,Math.floor(seconds/60)%60];
 return <><span className="yr-label">{t.countdown}</span>{seconds?<div className="yr-clock" role="timer" aria-live="off" aria-label={t.countdown} dir="ltr">{values.map((value,i)=><span key={i}><strong>{new Intl.NumberFormat('en',{minimumIntegerDigits:2,useGrouping:false}).format(value)}</strong><small>{t.units[i]}</small></span>)}</div>:<p>{t.arrived}</p>}<Flourish/></>;
}
function Panel({progress,range,active,index,reduced,children,className=''}:{progress:MotionValue<number>;range:number[];active:number;index:number;reduced:boolean;children:ReactNode;className?:string}){
 const opacity=useRange(progress,range,[0,1,1,0]);const y=useRange(progress,range,[55,0,-8,-70]);
 return <motion.div className={`yr-story-panel ${className}`} style={reduced?undefined:{opacity,y}} aria-hidden={!reduced&&active!==index} inert={!reduced&&active!==index}>{children}</motion.div>;
}
function AmmanJourney({lang,ready}:{lang:Lang;ready:boolean}){
 const t=words[lang],reduced=!!useReducedMotion(),ref=useRef<HTMLElement>(null);const [active,setActive]=useState(0);
 const {scrollYProgress:p}=useScroll({target:ref,offset:['start start','end end']});
 useMotionValueEvent(p,'change',value=>setActive(value<.17?0:value<.34?1:value<.52?2:value<.73?3:4));
 const night=useRange(p,[.59,.86],[0,1]);const sky=useRange(p,[0,.65,1],[1.04,1.09,1.04]);const backdropY=useRange(p,[0,1],['0%','-3%']);
 const darkness=useRange(p,[.64,.93],[0,.35]);const messagePaper=useRange(p,[.12,.25,.37],[0,.87,0]);
 const daylight=useRange(p,[.55,.82],[1,0]);
 const maps=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(event.venue.mapQuery)}`;
 return <section ref={ref} id="yr-journey" className={`yr-journey ${reduced?'yr-journey-still':''}`} aria-label={lang==='ar'?'حكاية فرحتنا':'Our wedding journey'}><div className="yr-journey-sticky">
  <motion.div className="yr-world" style={reduced?undefined:{scale:sky,y:backdropY}} aria-hidden="true"><img src="/invitations/yousef-rama/amman-day.webp" alt="" width="1672" height="941" fetchPriority="high"/><motion.img src="/invitations/yousef-rama/amman-night.webp" alt="" width="1672" height="941" style={{opacity:reduced?0:night}}/><motion.div className="yr-day-wash" style={{opacity:reduced?1:daylight}}/><motion.div className="yr-night-shade" style={{opacity:reduced?0:darkness}}/></motion.div>
  <motion.div className="yr-paper-wash" style={{opacity:reduced?0:messagePaper}} aria-hidden="true"/>
  <div className="yr-story-content">
   <Panel progress={p} range={[-.02,0,.11,.17]} active={active} index={0} reduced={reduced} className="yr-name-scene"><span className="yr-label">{t.together}</span><Flourish/><motion.h1 lang="ar" dir="rtl" initial={false} animate={{opacity:ready?1:0,y:ready?0:24}} transition={{duration:1.5,delay:.2,ease:[.22,1,.36,1]}}>يوسف <span>و</span> راما</motion.h1><p className="yr-english-names" lang="en" dir="ltr">Yousef &amp; Rama</p><p className="yr-main-invite">{t.invite}</p><time className="yr-numeric-date" dateTime={event.eventDate} dir="ltr">18 <i>•</i> 06 <i>•</i> 2027</time><span className="yr-scroll-note">{t.journey}<i/></span></Panel>
   <Panel progress={p} range={[.15,.20,.28,.34]} active={active} index={1} reduced={reduced} className="yr-message-scene"><span className="yr-label">{t.messageLabel}</span><h2><Lines text={t.messageTitle}/></h2><Flourish/><p>{t.message}</p><small>{t.messageNote}</small></Panel>
   <Panel progress={p} range={[.32,.37,.45,.52]} active={active} index={2} reduced={reduced} className="yr-countdown-scene"><Countdown lang={lang}/></Panel>
   <Panel progress={p} range={[.50,.55,.68,.73]} active={active} index={3} reduced={reduced} className="yr-details-scene"><div className="yr-event-paper"><Corners/><span className="yr-label">{t.details}</span><p className="yr-event-weekday">{t.friday}</p><h2>{t.date}</h2><time dateTime={event.eventDate}>{t.time}<small>{t.timezone}</small></time><Flourish/><h3>{event.venue.name[lang]}</h3><p className="yr-venue-address">{event.venue.address[lang]}</p><a className="yr-link" href={maps} target="_blank" rel="noopener noreferrer"><MapPin size={17}/>{t.map}<ArrowUpRight size={21}/></a><button className="yr-link" onClick={downloadCalendar}><CalendarDays size={17}/>{t.calendar}<ArrowRight size={21}/></button></div></Panel>
   <Panel progress={p} range={[.71,.79,.97,1.1]} active={active} index={4} reduced={reduced} className="yr-evening-scene"><span className="yr-label">{t.eveningLabel}</span><h2><Lines text={t.evening}/></h2><Flourish/><p>{t.eveningNote}</p></Panel>
  </div>
 </div></section>;
}
function FashionDrawing(){return <svg className="yr-fashion" viewBox="0 0 300 260" fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"><path d="M77 15c-8 0-11 14-5 20 7 6 17-1 16-11-1-5-4-9-11-9Zm-7 28-19 10-13 86 13 3 15-61-4 142 16 0 3-91 7 91h17L98 82l13 60 13-4-20-85-20-10M75 45l6 40 7-40M77 48l5 9 6-9m-6 9v35M66 71l16 23 16-24M62 120h41M63 227l-3 10h18l1-10m11 0 3 10h19l-8-10"/><path d="M215 18c-9-2-17 4-16 16 1 10 16 13 22 4 4-8 2-17-6-20Zm-13 33-14 12-9 44 12 3 9-30 3 29-35 121c29 18 81 18 109 0l-36-121 2-29 9 30 13-3-10-44-14-12M201 54l12 13 11-13m-12 13-10 40m12-39 26 39M201 110c12 5 26 5 39 0M182 206c27 11 55 11 83 0M191 186l14-63m48 63-17-63M207 238v10m23-10v10M194 251h14m22 0h16"/></g><path d="M131 140h28m-14-14v28" stroke="currentColor" strokeWidth=".6"/></svg>;}
function Memory({index,progress,lang}:{index:number;progress:MotionValue<number>;lang:Lang}){
 const reduced=useReducedMotion(),start=index*.33;const x=useRange(progress,[start,start+.12,start+.32],['0vw','0vw',index===1?'75vw':'-75vw']);const rotate=useRange(progress,[start,start+.12,start+.32],[index===1?4:-4,index===1?2:-2,index===1?18:-17]);const y=useRange(progress,[start,start+.32],[0,-80]);const opacity=useRange(progress,[start+.21,start+.33],[1,0]);
 return <motion.figure className={`yr-memory yr-memory-${index}`} style={reduced?undefined:{x:index===2?0:x,y:index===2?0:y,rotate:index===2?-3:rotate,opacity:index===2?1:opacity,zIndex:3-index}}><div><img src={`/invitations/yousef-rama/${['memory-walk','memory-window','memory-flowers'][index]}.webp`} alt={photoAlt[lang][index]} width="900" height="1200" loading="lazy"/></div><figcaption>{words[lang].captions[index]}</figcaption></motion.figure>;
}
function Memories({lang}:{lang:Lang}){
 const t=words[lang],ref=useRef<HTMLElement>(null),reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start start','end end']});
 return <section ref={ref} className={`yr-memories ${reduced?'yr-memories-still':''}`} aria-label={t.photosLabel}><div className="yr-memories-sticky"><div className="yr-memories-copy"><span className="yr-label">{t.photosLabel}</span><h2><Lines text={t.photos}/></h2><Flourish/><p>{t.photoNote}</p><small>{t.photoHint}<ArrowRight size={22}/></small></div><div className="yr-photo-stack">{[0,1,2].map(index=><Memory key={index} index={index} progress={scrollYProgress} lang={lang}/>)}</div></div></section>;
}
function Finale({lang}:{lang:Lang}){
 const t=words[lang],ref=useRef<HTMLElement>(null),reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start end','end end']});const scale=useRange(scrollYProgress,[0,1],[1.12,1]);const y=useRange(scrollYProgress,[0,1],[35,-20]);const opacity=useRange(scrollYProgress,[.18,.5],[0,1]);
 return <section className="yr-finale" ref={ref}><div className="yr-finale-sticky"><motion.img src="/invitations/yousef-rama/finale-v2.webp" alt={lang==='ar'?'مشهد مولّد لأمسية دافئة في شوارع عمّان':'Generated warm evening street in Amman'} width="1672" height="941" loading="lazy" style={reduced?undefined:{scale,y}}/><motion.div className="yr-final-words" style={reduced?undefined:{opacity}}><span className="yr-label">{t.closing}</span><h2 lang="ar" dir="rtl">يوسف <Heart size={28} strokeWidth={1}/> راما</h2><time dateTime={event.eventDate} dir="ltr">18.06.2027</time><Flourish/><p lang="en">Your presence is part of our story.</p></motion.div></div></section>;
}
function utc(date:Date){return date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');}
function showDate(){const story=document.getElementById('yr-journey');if(!story)return;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){document.querySelector('.yr-event-paper')?.scrollIntoView({block:'center'});return;}const top=story.getBoundingClientRect().top+window.scrollY;window.scrollTo({top:top+(story.offsetHeight-window.innerHeight)*.6,behavior:'smooth'});}
function downloadCalendar(){
 const calendar=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Invitea//Yousef and Rama//EN','BEGIN:VEVENT','UID:yousef-rama-wedding-invitea',`DTSTAMP:${utc(new Date())}`,`DTSTART:${utc(new Date(event.eventDate))}`,`DTEND:${utc(new Date(event.endDate))}`,'SUMMARY:Yousef & Rama - Wedding','LOCATION:The Ritz-Carlton\, Amman\, 5th Circle\, Al Kindi Street','DESCRIPTION:We look forward to celebrating with you.','END:VEVENT','END:VCALENDAR',''].join('\r\n');const url=URL.createObjectURL(new Blob([calendar],{type:'text/calendar;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='yousef-rama-wedding.ics';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function YousefRamaInvitation(){
 const {lang,setLang}=useLanguage(),t=words[lang],reduced=!!useReducedMotion();const [intro,setIntro]=useState(true);const audio=useRef<HTMLAudioElement>(null);const sound=useWeddingMusic(audio,true,.18),{playing}=sound;
 useEffect(()=>{document.title=lang==='ar'?'زفاف يوسف وراما · ١٨ يونيو ٢٠٢٧':'Yousef & Rama · 18 June 2027';},[lang]);
 useEffect(()=>{const timer=setTimeout(()=>setIntro(false),reduced?600:2700);return()=>clearTimeout(timer);},[reduced]);
 useEffect(()=>{if(!intro)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};},[intro]);
 return <div className={`yousef-rama ${reduced?'yr-reduced':''}`} dir={lang==='ar'?'rtl':'ltr'} lang={lang}>
  <div className="yr-grain" aria-hidden="true"/>
  <audio ref={audio} src={event.music.src} autoPlay loop preload="auto" onPlaying={sound.onPlaying} onPause={sound.onPause} onError={sound.onError}/>
  <AnimatePresence onExitComplete={()=>document.getElementById('yr-main')?.focus({preventScroll:true})}>{intro&&<motion.section className="yr-opening" aria-labelledby="yr-bismillah" initial={false} exit={reduced?{opacity:0}:{opacity:0,y:-35}} transition={{duration:reduced?.15:.8,ease:[.22,1,.36,1]}}><Corners/><motion.div initial={reduced?false:{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{duration:1.4,ease:[.22,1,.36,1]}}><h1 id="yr-bismillah" lang="ar" dir="rtl">بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ</h1><Flourish/><motion.p initial={reduced?false:{opacity:0}} animate={{opacity:1}} transition={{delay:.7,duration:1}}>{t.opening}</motion.p></motion.div><button className="yr-opening-skip" onClick={()=>setIntro(false)}>{t.skip}<ArrowRight size={19}/></button></motion.section>}</AnimatePresence>
  <div inert={intro} aria-hidden={intro}>
   <a className="yr-skip" href="#yr-main">{t.skipContent}</a>
   <header className="yr-nav"><a className="yr-initials" href="#yr-main" aria-label={event.names[lang]} dir="ltr">Y <em>&</em> R</a><nav aria-label={lang==='ar'?'أقسام الدعوة':'Invitation sections'}><a href="#yr-journey" onClick={event=>{event.preventDefault();showDate();}}>{t.navDate}</a><a href="#yr-rsvp">{t.navReply}</a></nav><button className="yr-language" onClick={()=>setLang(lang==='ar'?'en':'ar')}>{lang==='ar'?'EN':'عربي'}</button></header>
   <main id="yr-main" tabIndex={-1}>
    <AmmanJourney lang={lang} ready={!intro}/>
    <section className="yr-evening" id="yr-evening"><Reveal className="yr-section-heading"><span className="yr-label">{t.eveningNote}</span><h2>{t.schedule}</h2><p>{t.scheduleNote}</p></Reveal><ol className="yr-timeline">{event.schedule.map((step,i)=><Reveal as="li" key={step.time} className="yr-timeline-step"><span className="yr-step-number">0{i+1}</span><time dateTime={step.time} dir="ltr">{new Intl.DateTimeFormat('en',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:'UTC'}).format(new Date(`2000-01-01T${step.time}:00Z`))}</time><div><h3>{step.title[lang]}</h3><p>{step.text[lang]}</p></div></Reveal>)}</ol></section>
    <section className="yr-dress"><Reveal className="yr-dress-copy"><span className="yr-label">{t.dressLabel}</span><h2>{t.dress}</h2><Flourish/><p>{t.dressText}</p><small lang="en">A timeless evening. An elegant you.</small></Reveal><Reveal><FashionDrawing/></Reveal></section>
    <Memories lang={lang}/>
    <section className="yr-rsvp" id="yr-rsvp"><Reveal className="yr-rsvp-copy"><span className="yr-label">{t.rsvpLabel}</span><h2>{t.rsvp}</h2><Flourish/><p>{t.rsvpText}</p><span className="yr-rsvp-monogram" aria-hidden="true" dir="ltr">Y & R</span></Reveal><GuestReply slug={event.slug} labels={{ar:{submit:'تأكيد الحضور',thanks:'شكراً لك، ننتظرك بكل حب.',thankYou:'وصل ردّك إلى يوسف وراما.'},en:{submit:'Confirm attendance',thanks:'Thank you. We cannot wait to welcome you.',thankYou:'Your reply is with Yousef & Rama.'}}}/></section>
    <Finale lang={lang}/>
   </main>
   <footer className="yr-footer"><a href={`/${lang}`}>{t.credit}</a><span dir="ltr">Y & R · 18.06.2027</span><details><summary>{t.musicCredit}</summary><p>“{event.music.title}” · {event.music.composer}. Recording by <a href={event.music.source} target="_blank" rel="noopener noreferrer">{event.music.artist}</a>, <a href={event.music.license} target="_blank" rel="noopener noreferrer">{event.music.licenseName}</a>. {lang==='ar'?'نسخة مضغوطة للصوت الأصلي.':'Audio compressed for the web.'}</p></details></footer>
  </div>
  <button className={`yr-music ${playing?'is-playing':''}`} data-music-control onClick={sound.toggle} aria-label={playing?t.pause:t.sound} aria-pressed={playing}>{playing?<Pause size={16}/>:<Music2 size={16}/>}<span>{t.sound}</span></button><span className="yr-screen-reader" role="status">{sound.failed?t.musicError:''}</span>{sound.blocked&&!playing&&<span className="yr-opening-sound-note" role="status">{t.musicHint}</span>}
 </div>;
}
