import {arabicCopy} from './arabicCopy';
export const copy = {
 en: {
 experienceIndex:'I / THE EXPERIENCE',workIndex:'II / SELECTED WORK',projectNames:'Lelyan & Rama',
 nav:['Our Invitations','How It Works','Services','FAQ'],start:'Start Your Invitation',view:'View Invitations',preview:'Preview Invitation',close:'Close',menu:'Menu',skip:'Skip to content',
 brandOrigin:'BESPOKE BY NATURE. DIGITAL BY DESIGN.',brandPaperNote:'A thoughtful beginning.',brandLetter:'Something beautiful begins with you.',brandLetterNote:'Your occasion. Your story. Your own invitation website.',brandEnvelopeLabel:'PERSONALLY CREATED. BEAUTIFULLY SHARED.',brandSceneCaption:'A little glimpse into the art of inviting.',brandSignature:'THE ART OF INVITING',openEnvelope:'Open the Invitéa experience',closeEnvelope:'Close the envelope',eyebrow:'A DIGITAL INVITATION STUDIO',hero:['Your invitation,','beautifully','online.'],intro:'Custom invitation websites, created for your occasion.',heroNote:'You tell us your story. We turn it into a beautiful beginning.',scroll:'SCROLL TO DISCOVER',made:'DESIGNED WITH INTENTION · SHARED WITH LOVE',edition:'THE INVITÉA EXPERIENCE',
 productLabel:'MORE THAN AN INVITATION',productTitle:['One link.','Everything','they need.'],productBody:'A little world for your occasion. Beautifully designed, thoughtfully connected, and made entirely yours.',features:['RSVP','Location','Countdown','Gallery','Music','Schedule'],featureDescriptions:['A considered way for guests to say they will be there.','Make the journey effortless with your venue and directions.','Let the anticipation become part of the occasion.','A place for the photographs that tell your story.','Set the mood with a soundtrack chosen by you.','Every moment, in its own time.'],explore:'EXPLORE THE DETAILS',available:'Features are tailored to your invitation.',
 featuredLabel:'A REAL INVITÉA INVITATION',featuredTitle:['A moment worth','opening.'],graduation:'GRADUATION',project:'A graduation celebration',projectBody:'A soft, romantic invitation that begins with an envelope and unfolds into a celebration. An invitation with its own sense of occasion.',projectFeatures:['Animated opening','Event details','Live countdown','Location'],live:'VIEW LIVE',external:'Opens the live invitation in a new tab',customNote:'Have something different in mind? Every invitation begins with you.',
 occasionsLabel:'MADE FOR YOUR MOMENTS',occasionsTitle:['Every occasion.','Entirely yours.'],occasions:['Weddings','Engagements','Dinners','Birthdays','Graduations','Private Events','Corporate Events'],occasionsNote:'Big milestones. Intimate gatherings. And everything worth celebrating.',
 processLabel:'FROM THE FIRST HELLO',processTitle:['Simple from','start to share.'],steps:[{title:'Tell us your story',body:'Your occasion, your people, your vision. Share the details and the feeling you want to create.'},{title:'We create',body:'We design and build your invitation website, with room to review and refine every meaningful detail.'},{title:'You share',body:'Once approved and payment is complete, your invitation goes live. One beautiful link, ready for your guests.'}],
 rsvpLabel:'THE RSVP EXPERIENCE',rsvpTitle:['Beautiful for your guests.','Simple for you.'],rsvpBody:'Less chasing. More celebrating. Give your guests a simple way to respond, and keep the details together.',rsvpSteps:['Guest opens the invitation','Guest confirms attendance','Responses appear in your private dashboard'],rsvpDemo:'AN INVITÉA DETAIL',rsvpPrompt:'Will you be joining us?',rsvpYes:'Joyfully accept',rsvpNo:'Regretfully decline',rsvpThanks:'A thoughtful reply. A little less to plan.',rsvpNote:'Interactive illustration · no response is saved',rsvpReset:'Try again',
 whyLabel:'THE ART OF INVITING',whyTitle:'Personal by design.',why:[['Made around you','Your occasion sets the direction. Every detail has a reason.'],['Beautiful on every screen','An experience that feels just as considered in the palm of a hand.'],['We take care of the details','Design, development, and hosting. You enjoy the moment.']],
 faqLabel:'A FEW THINGS TO KNOW',faqTitle:'Consider it answered.',faqs:[['What exactly is a website invitation?','A dedicated website for your occasion, bringing your event details, location, countdown and selected interactive features together in one link.'],['Do I design it myself?','We handle the design and website creation. You share your occasion, preferred style and content, then review your invitation with us.'],['Can my invitation be in Arabic or English?','Yes. Your invitation can be Arabic, English, or bilingual, with the design thoughtfully adapted to each language.'],['How long does it take?','Standard delivery is up to 7 days after we receive the required payment, event details and assets. Urgent requests of 3 days or less depend on availability.'],['Can I request changes?','Two rounds of reasonable minor revisions are included. Our own errors are corrected free of charge and do not count as a revision. Larger changes are quoted separately.'],['How do payments work?','In Jordan, 40% confirms your booking; the remaining 60% is due after approval and before publication. International orders require 100% upfront. Payment instructions are shared privately after your order is agreed.'],['Can you add RSVP, music or a gallery?','Yes. RSVP, maps, music, galleries and other features can be included according to your agreed invitation scope.'],['How long will my invitation stay online?','Hosting is included with no scheduled expiry and no current renewal fee, subject to continued service and infrastructure availability. You can request removal.']],
 formLabel:'LET’S MAKE SOMETHING PERSONAL',formTitle:['It starts with','your occasion.'],formIntro:'Tell us a little about what you’re imagining. We’ll take it from there.',name:'Your name',event:'Your occasion',date:'Event date',language:'Invitation language',style:'Your preferred style',notes:'Anything else you have in mind?',featuresLabel:'THE LITTLE EXTRAS',optional:'Optional',choose:'Please select',languages:['English','Arabic','Bilingual'],styles:['Classic','Modern','Minimal','Romantic','Editorial','Custom'],formSubmit:'Prepare My Request',whatsapp:'Send Request on WhatsApp',copyRequest:'Copy Request',copied:'Request copied',requestReady:'Your story, ready to share.',requestNotice:'Our contact details are being finalised. You can copy your request now and share it with Invitéa when contact opens.',review:'Review your request',edit:'Edit request',privacy:'Your details are used only to respond to your inquiry.',error:'Please complete your name and occasion.',copyError:'Please select and copy the request below.',
 final:['Your occasion.','Your invitation.','Made for you.'],finalSmall:'SOMETHING BEAUTIFUL BEGINS WITH A HELLO.',footerDescriptor:'Custom website invitations.\nCreated with care, in Jordan.',footerExplore:'EXPLORE',footerConnect:'LET’S BEGIN',terms:'Terms & Conditions',privacyLink:'Privacy Policy',back:'Back to Invitéa',legalUpdated:'Last updated',contactSoon:'Contact details coming soon',rights:'© Invitéa',footerSmall:'AN INVITATION TO SOMETHING BEAUTIFUL.',loading:'Opening your invitation…',unavailable:'This invitation is not available.',returnHome:'Visit Invitéa',
 },
 ar: arabicCopy
};
