export type ProjectId='bassam-lana'|'yousef-rama'|'tareq-layan'|'omar-sara'|'lelyan-rama'|'zaffeh';
type Bilingual={en:string;ar:string};
export const projects:{id:ProjectId;name:Bilingual;occasion:Bilingual;description:Bilingual;image:string;imageAlt?:Bilingual;colors:string[];externalHref?:string;couple?:Bilingual;badge?:Bilingual}[]=[
 {id:'bassam-lana',name:{en:'Bassam & Lana',ar:'بسّام ولانا'},occasion:{en:'THE GILDED HOUR · AMMAN',ar:'أمسية من نور · عمّان'},description:{en:'Bronze doors open into a candlelit world. A journey through luminous arches, created for Bassam & Lana.',ar:'لبسّام ولانا؛ أبواب برونزية تفتح على عالم من النور، وحكاية تعبر بكم أقواس الأمسية حتى الفرح.'},image:'/invitations/bassam-lana/cover.webp',imageAlt:{en:'Original rendered bronze wedding salon doors with champagne light.',ar:'أبواب برونزية مولّدة بضوء دافئ من دعوة بسّام ولانا.'},colors:['#F6EEE0','#B18B54','#35261E'],badge:{en:'Immersive wedding design',ar:'دعوة بتجربة غامرة'}},
 {id:'yousef-rama',name:{en:'Yousef & Rama',ar:'يوسف وراما'},occasion:{en:'A CLASSIC AMMAN WEDDING',ar:'زفاف بطابع عمّاني كلاسيكي'},description:{en:'Warm Amman streets, quiet memories and a story that moves from afternoon into evening.',ar:'ليوسف وراما؛ دفء عمّان، وذكريات جميلة، وحكاية ترافقكم من ضوء النهار إلى جمال الأمسية.'},image:'/invitations/yousef-rama/cover-v2.webp',imageAlt:{en:'An original scene of warm street lights in an imagined old Amman evening.',ar:'مشهد مولّد لشوارع دافئة وأضواء أمسية مستوحاة من عمّان القديمة.'},colors:['#672D32','#F3E8D5','#626047'],badge:{en:'Cinematic wedding design',ar:'تصميم زفاف سينمائي'}},
 {id:'omar-sara',name:{en:'Omar & Sara',ar:'عمر وسارة'},occasion:{en:'WEDDING · AMMAN',ar:'زفاف · عمّان'},description:{en:'A midnight garden wedding. Candlelit details, ivory flowers and a celebration at Four Seasons Amman.',ar:'لعمر وسارة؛ أزهار عاجية، ضوء شموع، وأمسية تحتفي ببدايتهما في فورسيزونز عمّان.'},image:'/invitations/omar-sara/cover.webp',colors:['#162C38','#F1EDE4','#C7AD7F']},
 {id:'lelyan-rama',name:{en:'Lelyan & Rama',ar:'ليليان وراما'},occasion:{en:'GRADUATION',ar:'تخرّج'},description:{en:'A floral graduation invitation with an interactive envelope opening.',ar:'فرحة تخرّج ليليان وراما، بأزهار ناعمة وظرف يفتح بداية الحكاية.'},image:'/brand/graduation-envelope.webp',colors:['#9D455A','#F8E8E4','#D8C2A8'],externalHref:'https://lelyan-and-rama-invitation-production.up.railway.app/'},
 {id:'zaffeh',name:{en:'Zaffeh',ar:'زفّة'},couple:{en:'Basema & Aisha',ar:'بسمة وعائشة'},occasion:{en:'GRADUATION CELEBRATION',ar:'زفّة تخرّج'},description:{en:'Basema & Aisha’s joyful celebration, with playful artwork and a tap of confetti.',ar:'زفّة بسمة وعائشة؛ دعوة مرحة بتفاصيل مميزة ولمسة قصاصات ملوّنة عند الضغط.'},image:'/portfolio/zaffeh-cover.webp',imageAlt:{en:'Burgundy graduation caps and ivory diplomas for Basema and Aisha.',ar:'قبعتا تخرّج بالبرغندي وشهادتان عاجيتان لدعوة بسمة وعائشة.'},colors:['#6E2F3A','#F5DDC3','#D8C2A8'],externalHref:'https://zafeh-invitation-production.up.railway.app/'}
];
projects.push({id:'tareq-layan',name:{en:'Tareq & Layan',ar:'طارق وليان'},occasion:{en:'CLASSIC WEDDING',ar:'زفاف كلاسيكي'},description:{en:'Ivory paper, Polaroid memories and a date to uncover. A classic wedding design at The French Mansion.',ar:'ورق عاجي، وصور تحفظ اللحظة، وموعد تكتشفه بنفسك. دعوة كلاسيكية في القصر الفرنسي.'},image:'/invitations/tareq-layan/cover.webp',imageAlt:{en:'The French Mansion enhanced in soft golden light.',ar:'القصر الفرنسي بإضاءة ذهبية ناعمة.'},colors:['#424D3E','#FBF7ED','#AA8960'],badge:{en:'Classic wedding design',ar:'تصميم زفاف كلاسيكي'}});
export const findProject=(id:string|null|undefined)=>projects.find(project=>project.id===id);
export const portfolioWords={
 en:{label:'SELECTED INVITATIONS',title:['Distinct moments.','Beautifully invited.'],intro:'Every invitation has a world of its own. Explore our designs and tell us what you would love for yours.',view:'View invitation',order:'Request this style',badge:'Bespoke invitation',note:'A design you love is only the beginning. We create your invitation around your story.',custom:'Start your invitation',selected:'YOUR DESIGN REFERENCE',change:'Explore our work',referenceRequest:'Design reference',paletteRequest:'Theme colours'},
 ar:{label:'من أعمالنا',title:['فرحات مختلفة،','ودعوات تشبه أصحابها.'],intro:'دعوات متنوّعة، ولكل واحدة حكايتها وطابعها. شاهد تصاميمنا، وأخبرنا كيف تتخيّل دعوتك.',view:'شاهد الدعوة',order:'اطلب هذا الطابع',badge:'دعوة خاصة',note:'الطابع الذي أحببته بداية الحديث. نخصّص دعوتك لتروي حكايتك أنت.',custom:'لنبدأ دعوتك',selected:'الطابع الذي أحببته',change:'تصفّح أعمالنا',referenceRequest:'طابع مرجعي',paletteRequest:'ألوان الدعوة'}
};
export const paletteWords={
 en:{colors:'Your invitation palette',colorIntro:'Choose up to three colours. A considered starting point for your invitation.',add:'Add colour',remove:'Remove colour',customColor:'Custom colour',colorLimit:'Your palette is complete. Remove a colour to try another.',presets:'A few colours to inspire you'},
 ar:{colors:'ألوان تليق بمناسبتك',colorIntro:'اختر حتى ثلاثة ألوان تحبّها، لنبني حولها طابع دعوتك.',add:'أضف لوناً',remove:'إزالة اللون',customColor:'لون تختاره بنفسك',colorLimit:'اكتملت لوحتك بثلاثة ألوان. أزل أحدها إن رغبت في تجربة لون آخر.',presets:'درجات تلهم اختيارك'}
};
export const paletteSwatches=[
 {hex:'#6E2F3A',en:'Burgundy',ar:'برغندي'},{hex:'#F8F3EC',en:'Ivory',ar:'عاجي'},{hex:'#D8C2A8',en:'Champagne',ar:'شامبانيا'},
 {hex:'#AD8583',en:'Dusty rose',ar:'وردي هادئ'},{hex:'#AEA391',en:'Warm taupe',ar:'رمادي دافئ'},{hex:'#495449',en:'Olive',ar:'زيتوني'},
 {hex:'#394755',en:'Slate blue',ar:'أزرق رمادي'},{hex:'#352E2C',en:'Espresso',ar:'بني عميق'}
];
