import {ArrowRight,ArrowUpRight} from './EditorialArrow';
import { useEffect,useRef,useState,type ReactNode } from 'react';
import { motion,useMotionValueEvent,useReducedMotion,useScroll } from 'motion/react';
import { Menu,X,Plus,Check } from 'lucide-react';
import { useLanguage } from '../i18n';
import { rsvpVideo,useContact,safeUrl } from '../config';
import RequestForm from './RequestForm';
import Hero from './BrandHero';
import Portfolio from './Portfolio';
import GuestPhotoFeature from './GuestPhotoFeature';
import {PageThread,ScrollVisual} from './ScrollExperience';
import {HeroProductStory,OccasionsStory,ProcessStory,FinalStory,useStoryMotion,useScrollMap} from './ScrollStory';

export function Reveal({children,className=''}:{children:ReactNode;className?:string;delay?:number}){return <div className={className}>{children}</div>;}
export function Lines({lines,className=''}:{lines:string[];className?:string}){const reduce=useReducedMotion();return <>{lines.map((line,i)=><motion.span className={`text-mask ${className}`} key={line} initial={reduce?false:'hidden'} whileInView="visible" viewport={{once:true,amount:.1}}><motion.span variants={{hidden:{y:'30%',clipPath:'inset(0 -20% 100% -20%)'},visible:{y:0,clipPath:'inset(0 -20% 0% -20%)'}}} transition={{duration:.9,delay:i*.1,ease:[.22,1,.36,1]}}>{line}</motion.span></motion.span>)}</>;}
export function Logo(){return <span className="brand-logo"><img src="/brand/wordmark.png" alt="Invitéa" width="2048" height="683"/></span>;}
export function Divider(){const reduce=useReducedMotion();return <motion.div className="signature" aria-hidden="true" initial={reduce?false:{clipPath:'inset(0 50% 0 50%)'}} whileInView={{clipPath:'inset(0 0% 0 0%)'}} viewport={{once:true}} transition={{duration:1.2,ease:[.22,1,.36,1]}}><img src="/brand/divider.png" alt="" width="2172" height="724" loading="lazy"/></motion.div>;}
export function Navigation(){const {t,lang,setLang}=useLanguage();const [compact,setCompact]=useState(false);const [open,setOpen]=useState(false);const menuRef=useRef<HTMLButtonElement>(null);useEffect(()=>{const handler=()=>setCompact(window.scrollY>45);handler();window.addEventListener('scroll',handler,{passive:true});return()=>window.removeEventListener('scroll',handler);},[]);useEffect(()=>{if(!open)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);menuRef.current?.focus();}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[open]);const ids=['invitations','how-it-works','services','faq'];return <><a className="skip-link" href="#main">{t.skip}</a><header className={`navigation ${compact?'compact':''}`}><a href={`/${lang}`} className="logo-link" aria-label="Invitéa home"><Logo/></a><nav className="desktop-nav" aria-label={lang==='en'?'Main navigation':'القائمة الرئيسية'}>{t.nav.map((n,i)=><a key={n} href={`#${ids[i]}`}>{n}</a>)}</nav><div className="nav-actions"><button className="language-switch" onClick={()=>setLang(lang==='en'?'ar':'en')} aria-label={lang==='en'?'Switch to Arabic':'Switch to English'}><span className={lang==='en'?'selected':''}>EN</span><span className="language-slash">/</span><span lang="ar" className={lang==='ar'?'selected':''}>عربي</span></button><a className="nav-cta" href="#request">{t.start}<ArrowRight size={15}/></a><button ref={menuRef} className="menu-toggle" aria-label={open?t.close:t.menu} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>{open&&<nav className="mobile-menu" id="mobile-menu" aria-label={t.menu}>{t.nav.map((n,i)=><a key={n} href={`#${ids[i]}`} onClick={()=>setOpen(false)}>{n}<ArrowUpRight/></a>)}<a href="#request" onClick={()=>setOpen(false)}>{t.start}<ArrowRight/></a></nav>}</>;}
function Product(){
 const {t}=useLanguage();const [active,setActive]=useState(0);const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();
 const {scrollYProgress}=useScroll({target:ref,offset:['start center','end center']});
 useMotionValueEvent(scrollYProgress,'change',value=>{if(!reduced)setActive(Math.min(t.features.length-1,Math.floor(value*t.features.length)));});
 return <section ref={ref} className="product section-shell" id="services"><div className="section-top"><span className="eyebrow">{t.productLabel}</span><span className="tiny">{t.experienceIndex}</span></div><div className="product-grid"><div className="product-copy"><h2><Lines lines={t.productTitle}/></h2><p>{t.productBody}</p></div><div className="product-lab"><div className="feature-orbit" aria-hidden="true"/><ScrollVisual className="detail-motion" distance={45} rotation={2}><div className="detail-paper"><img className="detail-monogram" src="/brand/monogram.png" alt="" loading="lazy"/><span className="tiny">{t.explore}</span><div className="detail-rule"/><motion.h3 key={active} initial={reduced?false:{opacity:0}} animate={{opacity:1}} transition={{duration:.3}}>{t.features[active]}</motion.h3><p>{t.featureDescriptions[active]}</p><span className="detail-index">0{active+1} / 06</span></div></ScrollVisual><div className="feature-labels" role="group" aria-label={t.explore}>{t.features.map((feature,i)=><button key={feature} className={`feature-label label-${i} ${active===i?'active':''}`} aria-pressed={active===i} onClick={()=>setActive(i)}><span className="feature-dot"/>{feature}<span className="feature-line"/></button>)}</div></div></div><p className="product-footnote tiny">{t.available}</p><Divider/></section>;
}
function Occasions(){const {t}=useLanguage();const [hover,setHover]=useState(0);return <section className="occasions section-shell"><div className="occasions-intro"><span className="eyebrow">{t.occasionsLabel}</span><h2><Lines lines={t.occasionsTitle}/></h2><p>{t.occasionsNote}</p><div className={`occasion-motif motif-${hover%3}`} aria-hidden="true"><span/><span/><img src="/brand/envelope-mark.png" alt="" loading="lazy"/></div></div><div className="occasion-list">{t.occasions.map((occasion,i)=><a href="#request" key={occasion} onMouseEnter={()=>setHover(i)} onFocus={()=>setHover(i)}><span className="tiny">0{i+1}</span><span>{occasion}</span><ArrowUpRight size={25}/></a>)}</div></section>;}
function Process(){
 const {t}=useLanguage();const [active,setActive]=useState(0);const refs=useRef<Array<HTMLDivElement|null>>([]),section=useRef<HTMLElement>(null);const reduced=useReducedMotion();
 const {scrollYProgress}=useScroll({target:section,offset:['start center','end center']});
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(Number((e.target as HTMLElement).dataset.step));});},{rootMargin:'-25% 0px -40% 0px',threshold:0});refs.current.forEach(el=>el&&observer.observe(el));return()=>observer.disconnect();},[]);
 return <section ref={section} className="process section-shell" id="how-it-works"><div className="process-heading"><span className="eyebrow">{t.processLabel}</span><h2><Lines lines={t.processTitle}/></h2><span className="process-counter">0{active+1}<span>/ 03</span></span></div><div className="process-steps"><div className="timeline-track" aria-hidden="true"><motion.span style={{scaleY:reduced?1:scrollYProgress}}/></div>{t.steps.map((step,i)=><div className={`process-step ${active===i?'active':''}`} key={step.title} data-step={i} ref={el=>{refs.current[i]=el;}}><span className="step-number">0{i+1}</span><div><h3>{step.title}</h3><p>{step.body}</p></div></div>)}</div></section>;
}
function Rsvp(){const {t}=useLanguage();const enabled=useStoryMotion(),scene=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:scene,offset:['start end','end center']});const panelX=useScrollMap(scrollYProgress,[0,.6],[-65,0]);const panelScale=useScrollMap(scrollYProgress,[0,.6],[.95,1]);const panelMask=useScrollMap(scrollYProgress,[0,.6],['inset(0% 20% 0% 0%)','inset(0% 0% 0% 0%)']);const background=useScrollMap(scrollYProgress,[0,.55,1],['#F8F3EC','#EFE3D3','#F4EDE3']);const [reply,setReply]=useState('');const videoRef=useRef<HTMLVideoElement>(null);useEffect(()=>{const el=videoRef.current;if(!el)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches)el.play().catch(()=>{});else el.pause();});observer.observe(el);return()=>observer.disconnect();},[]);return <motion.section ref={scene} className="rsvp section-shell" style={{backgroundColor:enabled?background:undefined}}><ScrollVisual className="rsvp-visual" distance={35} rotation={2}><motion.div className="rsvp-panel-motion" style={{x:enabled?panelX:0,scale:enabled?panelScale:1,clipPath:enabled?panelMask:"none"}}>{rsvpVideo?<video ref={videoRef} src={rsvpVideo} muted loop playsInline controls poster="/brand/social.png"/>:<div className="rsvp-demo"><img src="/brand/monogram.png" alt="" loading="lazy"/><span className="tiny">{t.rsvpDemo}</span><div className="rsvp-demo-line"/>{reply?<div className="demo-reply" role="status"><Check size={28}/><h3>{t.rsvpThanks}</h3><button className="text-link" onClick={()=>setReply('')}>{t.rsvpReset}</button></div>:<><h3>{t.rsvpPrompt}</h3><button className="demo-button" onClick={()=>setReply('yes')}>{t.rsvpYes}<ArrowUpRight size={15}/></button><button className="demo-decline" onClick={()=>setReply('no')}>{t.rsvpNo}</button></>}<span className="demo-caption">{t.rsvpNote}</span></div>}</motion.div></ScrollVisual><Reveal className="rsvp-copy"><span className="eyebrow">{t.rsvpLabel}</span><h2><Lines lines={t.rsvpTitle}/></h2><p>{t.rsvpBody}</p><ol>{t.rsvpSteps.map((step,i)=><li key={step}><span>0{i+1}</span>{step}</li>)}</ol></Reveal></motion.section>;}
function Faq(){const {t}=useLanguage();return <section className="faq section-shell" id="faq"><div><span className="eyebrow">{t.faqLabel}</span><h2>{t.faqTitle}</h2></div><div className="faq-list">{t.faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>;}
export function Footer(){const {t,lang,setLang}=useLanguage();const contact=useContact();return <footer className="footer"><div className="footer-top"><p>{t.footerDescriptor}</p><span className="tiny">{t.footerSmall}</span></div><div className="footer-grid"><a href={`/${lang}`} className="footer-wordmark" aria-label="Invitéa">Invitéa</a><div><span className="tiny">{t.footerExplore}</span><a href={`/${lang}#invitations`}>{t.nav[0]}</a><a href={`/${lang}#how-it-works`}>{t.nav[1]}</a><a href={`/${lang}#faq`}>{t.nav[3]}</a></div><div><span className="tiny">{t.footerConnect}</span><a href={`/${lang}#request`}>{t.start}</a>{contact.instagram&&safeUrl(contact.instagram)&&<a href={safeUrl(contact.instagram)} target="_blank" rel="noopener noreferrer">Instagram ↗</a>}{contact.whatsapp&&<a href={`https://wa.me/${contact.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noopener noreferrer">WhatsApp ↗</a>}{contact.email&&<a href={`mailto:${contact.email}`}>{contact.email}</a>}</div></div><div className="footer-bottom"><span>{t.rights} {new Date().getFullYear()}</span><div><a href={`/${lang}/terms`}>{t.terms}</a><a href={`/${lang}/privacy`}>{t.privacyLink}</a><button onClick={()=>setLang(lang==='en'?'ar':'en')}>EN / عربي</button></div></div></footer>;}
export default function Home(){const {t}=useLanguage();return <div className="invitea-experience"><PageThread/><Navigation/><main id="main"><HeroProductStory fallback={<><Hero/><Product/></>}/><GuestPhotoFeature/><Portfolio/><OccasionsStory fallback={<Occasions/>}/><ProcessStory fallback={<Process/>}/><Rsvp/><section className="why section-shell"><span className="eyebrow">{t.whyLabel}</span><h2>{t.whyTitle}</h2><div>{t.why.map(([title,description],i)=><Reveal key={title} delay={i*.1}><span className="tiny">0{i+1}</span><h3>{title}</h3><p>{description}</p></Reveal>)}</div></section><Faq/><RequestForm/><FinalStory/></main><Footer/></div>;}
